### ISSUE TITLE
Incorrect Version and Repository URL

### ISSUE THREAD

**Issue by johni-aveva** [stepfunc/dnp3-no-serial#1]
This is related to:
<https://github.com/stepfunc/dnp3/issues/361>

1. The assembly versions should match the version of the Nuget package.
2. The RepositoryUrl for this release references the original dnp3 repo rather than the dnp3-no-serial repo.

**[assembly: AssemblyFileVersion("1.0.0.0")]**
[assembly: AssemblyInformationalVersion("1.0.0+7f8bcf1ee9c2ca6b7a0ce2b682651841e57331e1")]
[assembly: AssemblyProduct("dnp3")]
[assembly: AssemblyTitle("dnp3")]
**[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/stepfunc/dnp3.git")]**
**[assembly: AssemblyVersion("1.0.0.0")]**

**Comment by jadamcrain** [comment]
@johni-aveva I'll see what I can do to get the assembly versions to match the Nuget package for the next release. It's probably just a matter of generating the right data in our C# binding backend.

I believe that the repo URL is valid as is. There's no actual code in this repo. This repo is merely a build-script for the main repository with some compile-time flags to exclude serial support.

**Comment by jadamcrain** [comment]
The assembly version was easy. The code generator that adds this metadata was updated with a [patch release](https://github.com/stepfunc/oo_bindgen/blob/main/CHANGELOG.md). This new version information will get added in the following upcoming releases:

DNP3 1.6.0
Modbus 1.4.0

![image](https://github.com/stepfunc/dnp3-no-serial/assets/305813/57526153-556c-4804-bad4-cd0aa25e9495)

**Comment by johni-aveva** [comment]
Thanks, Adam.

Please consider this request closed.

John
________________________________
